apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: webapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: nodejs
          image: dilipopseng/nodeapptestsuite:12
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
