apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: webapps
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
